api:
  key: B508534ED20348F090B4D0AD637D3660
appearance:
  name: Volterra 400 Dual
devel:
  virtualPrinter:
    enabled: true
    hasChamber: true
    hasFilbox: true
    numExtruders: 2
plugins:
  VolterraFilamentSensor:
    _config_version: 2
  VolterraFirmwareUpdater:
    board_shortcode: 4D
  softwareupdate:
    _config_version: 6
serial:
  autoconnect: true
  baudrate: 115200
  disconnectOnErrors: false
  ignoreErrorsFromFirmware: true
  log: true
  port: /dev/ttyACM0
server:
  commands:
    serverRestartCommand: sudo service octoprint restart
    systemRestartCommand: sudo reboot now
    systemShutdownCommand: sudo shutdown now
  firstRun: false
  secretKey: iAwmTIdoJ8suaEewX118ZqGFplA5q5GN
  seenWizards:
    anywhere: 4
    corewizard: 3
system:
  actions:
  - action: streamon
    command: /home/pi/scripts/webcam start
    confirm: false
    name: Start video stream
  - action: streamoff
    command: /home/pi/scripts/webcam stop
    confirm: false
    name: Stop video stream
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    filbox: null
    name: ABS
  - bed: 60
    chamber: null
    extruder: 180
    filbox: null
    name: PLA
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http://127.0.0.1:8080/?action=snapshot
  stream: /webcam/?action=stream
  streamRatio: '4:3'
